[tool.poetry]
name = "flask-sandbox"
version = "0.1.0"
description = ""
authors = ["Robin Burri <rburri@c1r16s5.42lausanne.ch>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
Flask = "^2.3.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
